// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/licitacao": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/licitacao" | "/*";
  };
  "components/layout/SiteLayout.jsx": {
    id: "components/layout/SiteLayout";
    page: "/" | "/licitacao" | "/*";
  };
  "components/pages/Home.jsx": {
    id: "components/pages/Home";
    page: "/";
  };
  "components/pages/Licitacao.jsx": {
    id: "components/pages/Licitacao";
    page: "/licitacao";
  };
  "components/pages/NotFound.jsx": {
    id: "components/pages/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "components/layout/SiteLayout": typeof import("./src/components/layout/SiteLayout.jsx");
  "components/pages/Home": typeof import("./src/components/pages/Home.jsx");
  "components/pages/Licitacao": typeof import("./src/components/pages/Licitacao.jsx");
  "components/pages/NotFound": typeof import("./src/components/pages/NotFound.jsx");
};